# ============================================================
# Generate-StoredProcSQL.ps1
# Interactively builds a SQL stored procedure call script
# ============================================================

Clear-Host
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "   SQL Stored Procedure Script Generator" -ForegroundColor Cyan
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""

# ── Helper: prompt until non-empty input is received ─────────
function Read-Required {
    param (
        [string]$Prompt,
        [string]$Example = ""
    )
    do {
        if ($Example) {
            Write-Host "$Prompt (e.g. $Example)" -ForegroundColor Yellow -NoNewline
        } else {
            Write-Host "$Prompt" -ForegroundColor Yellow -NoNewline
        }
        $value = Read-Host " "
        if ([string]::IsNullOrWhiteSpace($value)) {
            Write-Host "  [!] This field is required. Please enter a value." -ForegroundColor Red
        }
    } while ([string]::IsNullOrWhiteSpace($value))
    return $value.Trim()
}

# ── Collect inputs ────────────────────────────────────────────
Write-Host "Please answer the following questions to generate your SQL script." -ForegroundColor White
Write-Host ""

# ITSM Number
$itsmNumber = Read-Required -Prompt "1. Enter the ITSM # (ticket/change number)" -Example "CHG0012345"

# MemberID
$memberID = Read-Required -Prompt "2. Enter the MemberID" -Example "M-987654"

# UserName
$userName = Read-Required -Prompt "3. Enter the UserName (network/AD login)" -Example "jdoe"

# Optional: stored procedure name (defaulted but overridable)
Write-Host ""
Write-Host "4. Enter the Stored Procedure name" -ForegroundColor Yellow -NoNewline
$spName = Read-Host " [default: dbo.usp_UpdateMemberAccess]"
if ([string]::IsNullOrWhiteSpace($spName)) {
    $spName = "dbo.usp_UpdateMemberAccess"
}

# ── Build timestamp & metadata ────────────────────────────────
$runDate   = Get-Date -Format "yyyy-MM-dd"
$runTime   = Get-Date -Format "HH:mm:ss"
$scriptBy  = $env:USERNAME

# ── Generate SQL ──────────────────────────────────────────────
$sql = @"
-- ============================================================
-- SQL Script generated by Generate-StoredProcSQL.ps1
-- Generated On : $runDate $runTime
-- Generated By : $scriptBy
-- ITSM #       : $itsmNumber
-- ============================================================

-- ── Variable Declarations ─────────────────────────────────────
DECLARE @ITSM#     NVARCHAR(50) = N'$itsmNumber';
DECLARE @MemberID  NVARCHAR(50) = N'$memberID';
DECLARE @UserName  NVARCHAR(50) = N'$userName';

-- ── Execute Stored Procedure ──────────────────────────────────
EXEC $spName
    @MemberID  = @MemberID,
    @UserName  = @UserName,
    @ITSM#     = @ITSM#;

-- ── End of Script ─────────────────────────────────────────────
"@

# ── Display result ────────────────────────────────────────────
Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "   Generated SQL Script" -ForegroundColor Cyan
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host $sql -ForegroundColor Green

# ── Save to file ──────────────────────────────────────────────
$safeITSM    = $itsmNumber -replace '[\\/:*?"<>|]', '_'
$outputFile  = "StoredProc_$safeITSM`_$($runDate -replace '-','').sql"
$outputPath  = Join-Path -Path $PSScriptRoot -ChildPath $outputFile

try {
    $sql | Out-File -FilePath $outputPath -Encoding UTF8
    Write-Host ""
    Write-Host "============================================================" -ForegroundColor Cyan
    Write-Host "  Script saved to:" -ForegroundColor White
    Write-Host "  $outputPath" -ForegroundColor Green
    Write-Host "============================================================" -ForegroundColor Cyan
}
catch {
    Write-Host ""
    Write-Host "[!] Could not save file: $_" -ForegroundColor Red
}

Write-Host ""
Write-Host "Done. Press any key to exit..." -ForegroundColor Gray
$null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
